import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
	{
		ignores: ['node_modules/**']
	},
	js.configs.recommended,
	...tseslint.configs.recommended,
	{
		files: ['**/*.ts', '**/*.mjs'],
		rules: {
			'arrow-parens': [
				'error',
				'as-needed',
				{
					requireForBlockBody: false
				}
			],
			eqeqeq: 'off',
			'arrow-body-style': ['error', 'as-needed'],
			'eol-last': ['error', 'never'],
			'brace-style': ['error', '1tbs', { allowSingleLine: true }],
			'comma-dangle': ['error', 'never'],
			'comma-spacing': ['error', { before: false, after: true }],
			'comma-style': ['error', 'last'],
			curly: ['error', 'multi-line', 'consistent'],
			'default-case-last': 'error',
			'dot-location': ['error', 'property'],
			'dot-notation': 'error',
			camelcase: 'off',
			'handle-callback-err': 'off',
			indent: ['error', 'tab', { SwitchCase: 1 }],
			'lines-between-class-members': ['error', 'always', { exceptAfterSingleLine: true }],
			'multiline-ternary': ['error', 'always-multiline'],
			'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
			'new-parens': 'error',
			'no-array-constructor': 'error',
			'no-caller': 'error',
			'no-console': 'off',
			'no-empty-function': 'off',
			'no-inline-comments': 'off',
			'no-eval': 'error',
			'no-extend-native': 'error',
			'no-extra-bind': 'error',
			'no-floating-decimal': 'error',
			'no-implied-eval': 'error',
			'no-lone-blocks': 'error',
			'no-lonely-if': 'off',
			'no-shadow': 'off',
			'no-trailing-spaces': 'error',
			'no-multi-spaces': 'error',
			'no-mixed-spaces-and-tabs': 'error',
			'no-multi-str': 'off',
			'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 0, maxBOF: 0 }],
			'no-new': 'error',
			'no-new-func': 'error',
			'no-new-object': 'error',
			'no-new-wrappers': 'error',
			'no-octal-escape': 'error',
			'no-proto': 'error',
			'no-return-assign': 'error',
			'no-self-compare': 'error',
			'no-sequences': 'error',
			'no-template-curly-in-string': 'error',
			'no-throw-literal': 'error',
			'no-undef-init': 'error',
			'no-unmodified-loop-condition': 'error',
			'no-unneeded-ternary': 'error',
			'no-unreachable': 'error',
			'no-unused-expressions': 'off',
			'no-use-before-define': 'off',
			'no-useless-call': 'error',
			'no-useless-computed-key': 'error',
			'no-useless-constructor': 'off',
			'no-useless-escape': 'error',
			'no-useless-return': 'off',
			'no-var': 'error',
			'no-void': 'error',
			'no-whitespace-before-property': 'error',
			'no-unused-vars': 'off',
			'no-redeclare': ['error'],
			'no-dupe-class-members': 'error',
			'no-loss-of-precision': 'error',
			'no-restricted-syntax': [
				'error',
				{
					selector: 'SwitchCase > BlockStatement ~ BreakStatement'
				}
			],
			'object-curly-newline': ['error', { multiline: true, consistent: true }],
			'object-curly-spacing': ['error', 'always'],
			'object-property-newline': ['error', { allowMultiplePropertiesPerLine: true }],
			'object-shorthand': ['warn', 'properties'],
			'operator-linebreak': ['error', 'after', { overrides: { '?': 'before', ':': 'before', '|>': 'before' } }],
			'padded-blocks': ['error', 'never'],
			'prefer-const': ['error', { destructuring: 'all' }],
			'prefer-promise-reject-errors': 'error',
			'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
			'quote-props': ['error', 'as-needed'],
			quotes: ['error', 'single'],
			'rest-spread-spacing': 'error',
			semi: ['error', 'always'],
			'semi-spacing': 'error',
			'space-before-blocks': 'error',
			'space-in-parens': ['error', 'never'],
			'space-infix-ops': 'error',
			'space-unary-ops': 'error',
			'space-before-function-paren': ['error', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
			'spaced-comment': ['error', 'always'],
			'symbol-description': 'error'
		}
	}
];